services:
  db-user:
    image: postgres:15
    container_name: db-user
    restart: always
    env_file:
      - ./services/user-service/.env
    ports:
      - "5432:5432"
    volumes:
      - db-user-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U avigo_user || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  db-notification:
    image: postgres:15
    container_name: db-notification
    restart: always
    env_file:
      - ./services/notification-service/.env
    ports:
      - "5433:5432"
    volumes:
      - db-notification-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U avigo_notifications || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  gateway-service:
    build:
      context: ./services/gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    env_file:
      - ./services/gateway-service/.env
    ports:
      - "8080:8080"

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      db-user:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file:
      - ./services/user-service/.env
    ports:
      - "8081:8081"

  #listing-service 8082:8082

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      db-notification:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file:
      - ./services/notification-service/.env
    ports:
      - "8087:8087"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    healthcheck:
      test: [ "CMD-SHELL", "echo srvr | nc localhost 2181 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:29092 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "9000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://gateway-service:8080/api/v1
    depends_on:
      - gateway-service
    restart: unless-stopped

volumes:
  db-user-data:
  db-notification-data:
  zookeeper-data:
  zookeeper-logs:
  kafka-data: